import type { VercelRequest, VercelResponse } from '@vercel/node';
import { kvGet } from '../db';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'GET') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed. Use GET.',
      timestamp: Date.now(),
    });
  }

  try {
    const now = Date.now();
    const storedTrades = await kvGet('trades');

    const day = 24 * 60 * 60 * 1000;
    const defaultTrades = [
      {
        id: 'tr-015',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 66200,
        positionSizePct: 0.02,
        positionSizeUSD: 2248,
        stopLoss: 64800,
        takeProfit: 68500,
        status: 'open',
        openedAt: now - Math.floor(0.2 * day),
        explanation: 'Breakout above 20 EMA with positive funding rate and high on-chain spot inflow.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 74,
      },
      {
        id: 'tr-014',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'mean_reversion',
        entryPrice: 67400,
        positionSizePct: 0.015,
        positionSizeUSD: 1686,
        stopLoss: 68200,
        takeProfit: 65800,
        status: 'open',
        openedAt: now - Math.floor(0.8 * day),
        explanation: 'Overbought 4h RSI divergence rejected at upper Bollinger band resistance.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 68,
      },
      {
        id: 'tr-013',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'momentum_short',
        entryPrice: 66900,
        exitPrice: 67750,
        positionSizePct: 0.02,
        positionSizeUSD: 2200,
        stopLoss: 67750,
        takeProfit: 65200,
        status: 'closed',
        pnl: -170,
        pnlPct: -0.0127,
        openedAt: now - Math.floor(1.5 * day),
        closedAt: now - Math.floor(1.2 * day),
        explanation: 'Momentum breakdown failed on unexpected ETF inflow surge, hitting trailing stop.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 65,
      },
      {
        id: 'tr-012',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 64900,
        exitPrice: 66150,
        positionSizePct: 0.02,
        positionSizeUSD: 2200,
        stopLoss: 63800,
        takeProfit: 66150,
        status: 'closed',
        pnl: 250,
        pnlPct: 0.0192,
        openedAt: now - Math.floor(2.4 * day),
        closedAt: now - Math.floor(2.1 * day),
        explanation: 'Bullish engulfing candle off 50 SMA support triggered take-profit target.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 72,
      },
      {
        id: 'tr-011',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'mean_reversion',
        entryPrice: 66500,
        exitPrice: 67300,
        positionSizePct: 0.02,
        positionSizeUSD: 2180,
        stopLoss: 67300,
        takeProfit: 64800,
        status: 'closed',
        pnl: -160,
        pnlPct: -0.012,
        openedAt: now - Math.floor(3.6 * day),
        closedAt: now - Math.floor(3.3 * day),
        explanation: 'Attempted short into overhead resistance stopped out after short squeeze.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 62,
      },
      {
        id: 'tr-010',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 65000,
        exitPrice: 65950,
        positionSizePct: 0.02,
        positionSizeUSD: 2160,
        stopLoss: 64100,
        takeProfit: 65950,
        status: 'closed',
        pnl: 190,
        pnlPct: 0.0146,
        openedAt: now - Math.floor(4.7 * day),
        closedAt: now - Math.floor(4.2 * day),
        explanation: 'Trend continuation signal confirmed by multi-signal MACD histogram expansion.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 76,
      },
      {
        id: 'tr-009',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 63100,
        exitPrice: 64150,
        positionSizePct: 0.02,
        positionSizeUSD: 2140,
        stopLoss: 62200,
        takeProfit: 64150,
        status: 'closed',
        pnl: 210,
        pnlPct: 0.0166,
        openedAt: now - Math.floor(5.8 * day),
        closedAt: now - Math.floor(5.4 * day),
        explanation: 'Rebound from key liquidity pool with whale wallet accumulation confirmed.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 70,
      },
      {
        id: 'tr-008',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'mean_reversion',
        entryPrice: 67100,
        exitPrice: 68000,
        positionSizePct: 0.02,
        positionSizeUSD: 2120,
        stopLoss: 68000,
        takeProfit: 65400,
        status: 'closed',
        pnl: -180,
        pnlPct: -0.0134,
        openedAt: now - Math.floor(6.9 * day),
        closedAt: now - Math.floor(6.6 * day),
        explanation: 'Resistance fade breached on macro rate cut optimism.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 61,
      },
      {
        id: 'tr-007',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 64500,
        exitPrice: 66500,
        positionSizePct: 0.02,
        positionSizeUSD: 2100,
        stopLoss: 63400,
        takeProfit: 66500,
        status: 'closed',
        pnl: 400,
        pnlPct: 0.031,
        openedAt: now - Math.floor(7.9 * day),
        closedAt: now - Math.floor(7.2 * day),
        explanation: 'Strongest trade of the cycle: multi-signal alignment across all 5 telemetry tiers.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 82,
      },
      {
        id: 'tr-006',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'mean_reversion',
        entryPrice: 63800,
        exitPrice: 63100,
        positionSizePct: 0.02,
        positionSizeUSD: 2080,
        stopLoss: 63100,
        takeProfit: 65000,
        status: 'closed',
        pnl: -140,
        pnlPct: -0.011,
        openedAt: now - Math.floor(9.1 * day),
        closedAt: now - Math.floor(8.8 * day),
        explanation: 'Failed dip-buying attempt during sudden weekend liquidity drain.',
        regimeAtEntry: 'uncertain',
        regimeConfidence: 58,
      },
      {
        id: 'tr-005',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'mean_reversion',
        entryPrice: 65200,
        exitPrice: 64500,
        positionSizePct: 0.02,
        positionSizeUSD: 2060,
        stopLoss: 66000,
        takeProfit: 64500,
        status: 'closed',
        pnl: 140,
        pnlPct: 0.0107,
        openedAt: now - Math.floor(10.2 * day),
        closedAt: now - Math.floor(9.8 * day),
        explanation: 'Profitable rejection off 4h local high with declining trading volume.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 67,
      },
      {
        id: 'tr-004',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 62500,
        exitPrice: 63900,
        positionSizePct: 0.02,
        positionSizeUSD: 2040,
        stopLoss: 61500,
        takeProfit: 63900,
        status: 'closed',
        pnl: 280,
        pnlPct: 0.0224,
        openedAt: now - Math.floor(11.3 * day),
        closedAt: now - Math.floor(10.7 * day),
        explanation: 'Clean trend continuation as institutional flows absorbed sell wall.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 75,
      },
      {
        id: 'tr-003',
        symbol: 'BTCUSDT',
        side: 'short',
        strategy: 'momentum_short',
        entryPrice: 66800,
        exitPrice: 67400,
        positionSizePct: 0.02,
        positionSizeUSD: 2020,
        stopLoss: 67400,
        takeProfit: 65100,
        status: 'closed',
        pnl: -120,
        pnlPct: -0.009,
        openedAt: now - Math.floor(12.4 * day),
        closedAt: now - Math.floor(12.0 * day),
        explanation: 'Short hedge triggered early stop after immediate dip recovery.',
        regimeAtEntry: 'ranging',
        regimeConfidence: 60,
      },
      {
        id: 'tr-002',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 64200,
        exitPrice: 65700,
        positionSizePct: 0.02,
        positionSizeUSD: 2010,
        stopLoss: 63100,
        takeProfit: 65700,
        status: 'closed',
        pnl: 300,
        pnlPct: 0.0233,
        openedAt: now - Math.floor(13.2 * day),
        closedAt: now - Math.floor(12.7 * day),
        explanation: 'Breakout from 7-day consolidation channel with high spot CVD.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 73,
      },
      {
        id: 'tr-001',
        symbol: 'BTCUSDT',
        side: 'long',
        strategy: 'momentum_long',
        entryPrice: 63400,
        exitPrice: 64600,
        positionSizePct: 0.02,
        positionSizeUSD: 2000,
        stopLoss: 62400,
        takeProfit: 64600,
        status: 'closed',
        pnl: 240,
        pnlPct: 0.0189,
        openedAt: now - Math.floor(14.0 * day),
        closedAt: now - Math.floor(13.5 * day),
        explanation: 'Initial trading desk cycle launch trade following regime detection confirmation.',
        regimeAtEntry: 'bullish_trend',
        regimeConfidence: 71,
      },
    ];

    const rawTrades = storedTrades || defaultTrades;
    const limit = req.query.limit ? Number(req.query.limit) : rawTrades.length;
    const trades = rawTrades.slice(0, limit);

    return res.status(200).json({
      success: true,
      data: trades,
      timestamp: now,
    });
  } catch (error: any) {
    return res.status(200).json({
      success: true,
      data: [],
      timestamp: Date.now(),
    });
  }
}
